#!/usr/bin/python
# -*- coding: utf-8 -*-

# https://github.com/davidfmiller/bin


import sys
import os
import pwd
import getopt
import json
import tempfile
import subprocess

plainText = False
CATFDIR = os.path.dirname(os.path.realpath(__file__))

try:
  import pygments
  from pygments.lexers import guess_lexer, guess_lexer_for_filename
  from pygments import highlight
  from pygments.formatters import Terminal256Formatter
  from pygments.util import ClassNotFound
  import pygments_markdown_lexer

except ImportError, e: 
  sys.stderr.write("🚫  A required dependency is not installed;" + e + " see http://davidfmiller.github.io/bin for more information\n")
  plainText = True

def _catf(content, lexer = None, debug = False):
  """
  @param content (String) - the original contents of the file that should be sent to stdio
  @param debug (Boolean, optional) - flag controlling display of debug info
  """

  if plainText:
    sys.stdout.write(content)
  else:
    try:
      if lexer == None:
        lex = guess_lexer(content)
      else:
        lex = lexer

      if debug:
        sys.stderr.write(str(lex) + "\n")

      sys.stdout.write(highlight(content, lex, Terminal256Formatter()))

      # simply print the contents if no supported lexer is found
    except:
      sys.stdout.write(content)


if __name__ == '__main__':

  debug = False
  VERSION = "0.0.2"

  try:
    opts, args = getopt.getopt(sys.argv[1:], 'hudvl:', ['help', 'version'])
  except getopt.GetoptError:
    raise SystemExit("🚫  Incorrect usage")

  # assume no known lexer
  lex = None;

  for opt, arg in opts:

#    if opt == '-d':
#      debug = True

#    elif opt == '-n' or opt == '--numbers':
#      sys.stderr.write("Line #s coming soon\n");

    if opt == '-v' or opt == '--version':
      sys.stdout.write("🐱  v" + VERSION + "\n")
      sys.exit()

    elif opt == '-h' or opt == '--help':
      sys.stdout.write("""🐱  catf [-l json|html|xml|md] [filenames ...]
🌏  https://davidfmiller.github.io/bin\n""")
      sys.exit();

    elif opt == '-l':
      if arg == 'json':
        lex = pygments.lexers.JsonLexer()
      elif arg == 'html':
        lex = pygments.lexers.HtmlLexer()
      elif arg == 'xml':
        lex = pygments.lexers.XmlLexer()
      elif arg == 'md':
        lex = pygments_markdown_lexer.lexer.MarkdownLexer()

      else:
        raise SystemExit("🚫  Unknown lexer `" + arg + "`");

  if not sys.stdin.isatty():
    content = ''
    for line in sys.stdin:
      content += line
    _catf(content, lex, debug)

  else:

    if len(args) == 0:
      args = [os.getcwd()]

    for arg in args:

      try:
        path = os.path.abspath(os.path.join(os.getcwd(), arg))
      except OSError:
        raise SystemExit("🚫  Unable to determine current directory\n")

      if not os.path.exists(path):
        sys.stderr.write("🚫  File '" + arg + "' doesn't exist\n")
      else:

        name, extension = os.path.splitext(path)
        extension = extension.upper()

        if os.path.isdir(path):

          try:
            out,err = subprocess.Popen([CATFDIR + '/lsemoji', path], stdout=subprocess.PIPE).communicate()
            sys.stdout.write(out)
#            sys.stderr.write(err)
          except Exception as e:
#            sys.stderr.write(e.strerror)
            sys.stderr.write("🚫  Unable to read " + path + "\n")

        else:

          with open(path) as f:

            if extension == '.TEXTCLIPPING':

              try:
                out,err = subprocess.Popen([CATFDIR + '/text-clipping', path], stdout=subprocess.PIPE).communicate()
                sys.stdout.write(out)
              except:
                sys.stderr.write("🚫  Unable to read " + path + " as text clipping\n")

            else:

              contents = "".join(f.readlines())

              # force json lexer since pygments doesn't recognize .json extension
              if extension == '.JSON':
                _catf(contents, pygments.lexers.JsonLexer(), debug)
              else:
                _catf(contents, lex, debug)
