#!/bin/sh
# -*- coding: utf-8 -

# A simple script to open a git repository's remote host in your default web browser



if [ "$#" -ne 1 ]; then
REMOTE='origin'
#
else
  REMOTE="$1"
fi

URL=`(git remote get-url $REMOTE)`

if [ -z "$URL" ]; then
  exit 1
fi

open $URL