#!/usr/bin/env python
# -*- coding: utf-8 -

"""
A simple hack to open a git repository's remote host in your default web browser

TODO: Accept ≥ 1 filename argument and open that file's page, instead of repository home

"""

import sys
import subprocess
import re

out,err = subprocess.Popen(["git", "remote", "show", "origin"], stdout=subprocess.PIPE,stderr=subprocess.PIPE).communicate()
lines = out.splitlines()

# no git repo
if len(lines) == 0:
  sys.stderr.write("🚫  No git repo found\n")
  sys.exit(2)

# retrieve the line that has the fetch url, and strip all extraneous info
fetchLine = lines[1].split(':', 1)[1].strip()

url = ''

# github 
if re.search(r'github', fetchLine):
  url = fetchLine

# bitbucket
elif re.search(r'bitbucket', fetchLine):
  url = fetchLine.replace(':', '/').replace('git@', 'https://')

# unknown 
else:
  sys.stderr.write("🚫  Unknown remote origin " + fetchLine)
  sys.exit(2)

# if we're on os x open the url in the default web browser
try :
  subprocess.Popen(["open", url])

# if the `open` command is not found, print the url to stdout
except:
  sys.stdout.write("🌎  " + url + "\n")
