#!/bin/sh

# Export compressed copy of JPEG(s) using guetzli
# https://github.com/google/guetzli

cmd=`which guetzli`

# ensure guetzli is installed
if [[ $cmd == "" ]]
then
   >&2 echo "🚫  Install guetzli: https://github.com/google/guetzli"
   exit 1
fi


# if no arguments specified...
if [[ $1 == "" ]]
then
   >&2 echo "🚫  Usage: guetzler [path(s)]"
   exit 1
fi

# loop through all arguments
for arg in $@;
do

  # if a jpeg, export as `guetzler-{filename}.jpg`
  if [ -f "$arg" ];
  then
    f=`basename $arg`
    dir=`dirname $arg`

    echo $arg → $dir/guetzli-$f
    `$cmd $arg $dir/guetzli-$f`

  # if a directory, create sub-directory `guetzli` and export images there
  elif [ -d "$arg" ];
  then
    dir=`basename $1`

    format=*.jpg
    for i in $dir/$format;
    do

      outdir="`dirname $i`/guetzli"

      if [ ! -d "$outdir" ];
      then
        mkdir $outdir
      fi

      f=`basename $i`;
      echo $i → $outdir/$f;
      `$cmd $i $outdir/$f`
    done
  else
    >&2 echo "🚫  Invalid path \"$1\""
  fi

done
