#!/bin/sh


#
#
#


cmd=`which guetzli`

if [[ $cmd == "" ]]
then
   >&2 echo "🚫  Install guetzli: https://github.com/google/guetzli"
   exit 1
fi


if [[ $1 == "" ]]
then
   >&2 echo "🚫  No path(s) specified"
   exit 1
fi

for arg in $@;
do

  if [ -f "$arg" ];
  then
    f=`basename $arg`
    dir=`dirname $arg`

    echo $arg → $dir/guetzli-$f
    `$cmd $arg $dir/guetzli-$f`

  elif [ -d "$arg" ];
  then
    dir=`basename $1`

    format=*.jpg
    for i in $dir/$format;
    do

      outdir="`dirname $i`/guetzli"

#      echo "out $outdir"

      if [ ! -d "$outdir" ];
      then
#        echo "making $outdir"
        mkdir $outdir
      fi

      f=`basename $i`;
      echo $i → $outdir/$f;
      `$cmd $i $outdir/$f`
    done
  else
    >&2 echo "🚫  Invalid path \"$1\""
  fi

done
