#!/bin/sh

# Serve a folder via HTTP

PORT=0

# if no arguments specified...
if [[ $1 == "" ]]
then
  PORT=8081
else
  PORT="$1"

#    >&2 echo "🚫  Invalid port"
#    exit 1
 fi

echo "🌏 http://0.0.0.0:$PORT/"

err=$(python -m SimpleHTTPServer $PORT 2>&1)

if [[ $err ]];
then
   >&2 echo "🚫  Unable to listen on port $1"
   exit 1
fi