#!/usr/bin/env node

# https://github.com/davidfmiller/bin/

var fs = require('fs'),
    buf = fs.readFileSync('/dev/stdin').toString(),
    obj = JSON.parse(buf);

console.log(JSON.stringify(obj, null, 2));
