#!/bin/sh

if [ "$#" -eq 0 ]; then
  >&2 echo "🚫 uti [filename] [...]"
  exit 1
fi


for var in "$@"
do
  STR=`mdls -name kMDItemContentType $var`
  STR=`echo "$STR" | cut -d'"' -f 2`
  NAME=`basename $var`

  if [ "$#" -ne 1 ]; then
    echo "$NAME : $STR"
  else
    echo $STR
  fi

done
